// fixed navigation/add-page app.js
const DB_NAME='mahalliDB', DB_VERSION=3;
let db=null, route={name:'home',params:{}}, historyStack=[];
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const money=v=>Number(v||0).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2});
const nowLocal=()=>{const d=new Date(),p=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}T${p(d.getHours())}:${p(d.getMinutes())}`};
const uid=(p='id')=>`${p}_${Date.now()}_${Math.random().toString(36).slice(2,9)}`;
function toast(m){const x=$('#toast');if(!x)return;x.textContent=m;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2200)}
function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,DB_VERSION);r.onupgradeneeded=e=>{const d=e.target.result;['companies','customers','suppliers','purchases','expenses','payments','requests','trash','settings','meta'].forEach(n=>{if(!d.objectStoreNames.contains(n)){const s=d.createObjectStore(n,{keyPath:'id'});s.createIndex('createdAt','createdAt')}})};r.onsuccess=()=>{db=r.result;resolve(db)};r.onerror=()=>reject(r.error)})}
const store=(n,m='readonly')=>db.transaction(n,m).objectStore(n);
const getRecord=(n,id)=>new Promise((res,rej)=>{const r=store(n).get(id);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)});
const getAll=n=>new Promise((res,rej)=>{const r=store(n).getAll();r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)});
const putRecord=(n,o)=>new Promise((res,rej)=>{const r=store(n,'readwrite').put(o);r.onsuccess=()=>res(o);r.onerror=()=>rej(r.error)});
const deleteRecord=(n,id)=>new Promise((res,rej)=>{const r=store(n,'readwrite').delete(id);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)});
async function nextNumber(key,prefix=''){const m=await getRecord('meta',key),v=Number(m?.value||0)+1;await putRecord('meta',{id:key,value:v});return `${prefix}${String(v).padStart(4,'0')}`}
function go(name,params={},push=true){if(push&&route.name!==name)historyStack.push({...route,params:{...route.params}});route={name,params:{...params}};render()}
function back(){const p=historyStack.pop();if(p){route=p;render()}else home()}
function home(){historyStack=[];route={name:'home',params:{}};render()}
window.openAddCompany=()=>go('companyForm',{id:''});
window.openAddCustomer=(companyId='')=>go('customerForm',{id:'',companyId});
window.openAddExpense=()=>go('expenseForm',{id:''});
window.editCompany=id=>go('companyForm',{id});
window.editCustomer=(id,companyId='')=>go('customerForm',{id,companyId});
window.editExpense=id=>go('expenseForm',{id});
window.openCompany=id=>go('company',{id});
window.openCustomer=id=>go('customer',{id});
window.openPayments=()=>go('payments');
window.placeholder=t=>{const m=$('#modal');if(!m)return;m.classList.remove('hidden');m.innerHTML=`<div class="modal-box"><div class="modal-title">${esc(t)}</div><p class="muted">هذه الوحدة ستُستكمل في المرحلة التالية.</p><button class="btn btn-primary" onclick="closeModal()">حسنًا</button></div>`};
window.closeModal=()=>{const m=$('#modal');if(!m)return;m.classList.add('hidden');m.innerHTML=''};
async function render(){if(!db)return;const a=$('#app');if(!a)return;$('#backBtn')?.classList.toggle('hidden',route.name==='home');$('#homeBtn')?.classList.toggle('hidden',route.name==='home');a.innerHTML='';switch(route.name){case'home':return renderHome(a);case'companies':return renderCompanies(a);case'company':return renderCompany(a,route.params.id);case'companyForm':return renderCompanyForm(a,route.params.id);case'customerForm':return renderCustomerForm(a,route.params.id,route.params.companyId);case'customer':return renderCustomer(a,route.params.id);case'expenses':return renderExpenses(a);case'expenseForm':return renderExpenseForm(a,route.params.id);case'payments':return renderPayments(a);default:return home()}}
function renderHome(a){a.innerHTML=`<div class="home-title">محلّي</div><div class="home-grid"><button class="home-card" onclick="go('companies')"><span class="emoji">🏢</span>الشركات والعملاء</button><button class="home-card" onclick="placeholder('المشتريات')"><span class="emoji">🛒</span>المشتريات</button><button class="home-card" onclick="placeholder('الموردون')"><span class="emoji">🏭</span>الموردون</button><button class="home-card" onclick="go('expenses')"><span class="emoji">💸</span>المصروفات</button><button class="home-card" onclick="openPayments()"><span class="emoji">💰</span>الدفعات</button><button class="home-card" onclick="placeholder('التقارير')"><span class="emoji">📊</span>التقارير</button><button class="home-card" onclick="placeholder('البحث')"><span class="emoji">🔍</span>البحث</button><button class="home-card" onclick="placeholder('الإعدادات والنسخ الاحتياطي')"><span class="emoji">⚙️</span>الإعدادات والنسخ الاحتياطي</button></div>`}
async function renderCompanies(a){const cs=(await getAll('companies')).sort((x,y)=>String(y.createdAt||'').localeCompare(String(x.createdAt||'')));a.innerHTML=`<div class="section-head"><div class="section-title">الشركات والعملاء</div><button class="btn btn-primary" onclick="openAddCompany()">＋ إضافة شركة</button></div><input id="companySearch" class="search" placeholder="بحث باسم الشركة"><div id="company-list">${cs.length?cs.map(c=>`<div class="card searchable" data-search="${esc(c.name)}"><div class="row"><div><strong>${esc(c.name)}</strong><div class="muted">${esc(c.phone||'')}</div></div><div class="amount">${money(c.totalUSD)} $<br>${money(c.totalIQD)} د.ع</div></div><div class="list-actions"><button class="btn btn-light" onclick="openCompany('${c.id}')">فتح</button><button class="btn btn-light" onclick="editCompany('${c.id}')">تعديل</button><button class="btn btn-danger" onclick="deleteCompany('${c.id}')">حذف</button></div></div>`).join(''):'<div class="empty">لا توجد شركات بعد.</div>'}</div>`;$('#companySearch')?.addEventListener('input',e=>{const q=e.target.value.toLowerCase();document.querySelectorAll('#company-list .searchable').forEach(x=>x.style.display=String(x.dataset.search||'').toLowerCase().includes(q)?'':'none')})}
async function renderCompanyForm(a,id){const c=id?await getRecord('companies',id):{};a.innerHTML=`<div class="section-head"><div class="section-title">${id?'تعديل الشركة':'إضافة شركة'}</div></div><form id="companyFormPage" class="form"><div class="field"><label>اسم الشركة *</label><input id="companyName" required value="${esc(c.name||'')}"></div><div class="field"><label>الهاتف</label><input id="companyPhone" value="${esc(c.phone||'')}"></div><div class="field"><label>العنوان</label><input id="companyAddress" value="${esc(c.address||'')}"></div><div class="field"><label>ملاحظات</label><textarea id="companyNotes">${esc(c.notes||'')}</textarea></div><div class="form-actions"><button type="button" class="btn btn-light" onclick="back()">إلغاء</button><button type="submit" class="btn btn-primary">حفظ الشركة</button></div></form>`;$('#companyFormPage').addEventListener('submit',async e=>{e.preventDefault();const name=$('#companyName').value.trim();if(!name)return toast('اسم الشركة مطلوب');const old=id?await getRecord('companies',id):null;await putRecord('companies',{id:id||uid('company'),name,phone:$('#companyPhone').value.trim(),address:$('#companyAddress').value.trim(),notes:$('#companyNotes').value.trim(),createdAt:old?.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString(),totalUSD:old?.totalUSD||0,totalIQD:old?.totalIQD||0});toast('تم حفظ الشركة');go('companies',{},false)})}
async function renderCustomerForm(a,id,companyId){const c=id?await getRecord('customers',id):{};const cid=companyId||c.companyId||'';a.innerHTML=`<div class="section-head"><div class="section-title">${id?'تعديل العميل':'إضافة عميل'}</div></div><form id="customerFormPage" class="form"><div class="field"><label>اسم العميل *</label><input id="customerName" required value="${esc(c.name||'')}"></div><div class="field"><label>الهاتف</label><input id="customerPhone" value="${esc(c.phone||'')}"></div><div class="field"><label>العنوان</label><input id="customerAddress" value="${esc(c.address||'')}"></div><div class="field"><label>ملاحظات</label><textarea id="customerNotes">${esc(c.notes||'')}</textarea></div><div class="form-actions"><button type="button" class="btn btn-light" onclick="back()">إلغاء</button><button type="submit" class="btn btn-primary">حفظ العميل</button></div></form>`;$('#customerFormPage').addEventListener('submit',async e=>{e.preventDefault();const name=$('#customerName').value.trim();if(!name)return toast('اسم العميل مطلوب');const old=id?await getRecord('customers',id):null;const customer={id:id||uid('customer'),name,phone:$('#customerPhone').value.trim(),address:$('#customerAddress').value.trim(),notes:$('#customerNotes').value.trim(),companyId:cid||old?.companyId||null,accountNumber:old?.accountNumber||null,accountStatus:old?.accountStatus||'مفتوح',createdAt:old?.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()};await putRecord('customers',customer);toast('تم حفظ العميل');customer.companyId?go('company',{id:customer.companyId},false):go('companies',{},false)})}
async function renderCompany(a,id){const c=await getRecord('companies',id);if(!c)return home();const cs=(await getAll('customers')).filter(x=>x.companyId===id).sort((x,y)=>String(y.createdAt||'').localeCompare(String(x.createdAt||'')));a.innerHTML=`<div class="section-head"><div class="section-title">${esc(c.name)}</div><button class="btn btn-light" onclick="editCompany('${id}')">تعديل</button></div><div class="total-box"><div class="total">الدولار<strong>${money(c.totalUSD)} $</strong></div><div class="total">الدينار<strong>${money(c.totalIQD)} د.ع</strong></div></div><div class="actions" style="margin-bottom:12px"><button class="btn btn-primary" onclick="openAddCustomer('${id}')">＋ إضافة عميل</button><button class="btn btn-primary" onclick="placeholder('إضافة طلب')">＋ إضافة طلب</button><button class="btn btn-success" onclick="placeholder('إضافة دفعة للشركة')">💰 إضافة دفعة للشركة</button></div>${cs.length?cs.map(x=>`<div class="card"><div class="row"><div><strong>${esc(x.name)}</strong><div class="muted">${esc(x.phone||'')}</div></div></div><div class="list-actions"><button class="btn btn-light" onclick="openCustomer('${x.id}')">فتح</button><button class="btn btn-light" onclick="editCustomer('${x.id}','${id}')">تعديل</button></div></div>`).join(''):'<div class="empty">لا يوجد عملاء لهذه الشركة.</div>'}`}
async function renderCustomer(a,id){const c=await getRecord('customers',id);if(!c)return home();a.innerHTML=`<div class="section-head"><div class="section-title">${esc(c.name)}</div><button class="btn btn-light" onclick="editCustomer('${id}','${c.companyId||''}')">تعديل</button></div><div class="empty">صفحة حساب العميل الأساسية ستُستكمل في المرحلة التالية.</div>`}
async function renderExpenses(a){const xs=(await getAll('expenses')).sort((x,y)=>String(y.dateTime||'').localeCompare(String(x.dateTime||'')));a.innerHTML=`<div class="section-head"><div class="section-title">المصروفات</div><button class="btn btn-primary" onclick="openAddExpense()">＋ إضافة مصروف</button></div>${xs.length?xs.map(x=>`<div class="card"><div class="row"><strong>#${esc(x.number)}</strong><span>${esc(x.type)}</span></div><div>${money(x.usd)} $ | ${money(x.iqd)} د.ع</div><div class="muted">${esc(x.dateTime||'')}</div><div class="list-actions"><button class="btn btn-light" onclick="editExpense('${x.id}')">تعديل</button><button class="btn btn-danger" onclick="deleteExpense('${x.id}')">حذف</button></div></div>`).join(''):'<div class="empty">لا توجد مصروفات.</div>'}`}
async function renderExpenseForm(a,id){const x=id?await getRecord('expenses',id):{};a.innerHTML=`<div class="section-head"><div class="section-title">${id?'تعديل المصروف':'إضافة مصروف'}</div></div><form id="expenseFormPage" class="form"><div class="field"><label>النوع</label><input id="expenseType" value="${esc(x.type||'أخرى')}"></div><div class="field"><label>المبلغ *</label><input id="expenseAmount" type="number" step="0.01" min="0" required value="${x.originalAmount??''}"></div><div class="field"><label>العملة</label><select id="expenseCurrency"><option value="USD" ${x.currency==='USD'?'selected':''}>USD</option><option value="IQD" ${x.currency==='IQD'?'selected':''}>IQD</option></select></div><div class="field"><label>سعر الصرف *</label><input id="expenseRate" type="number" step="0.01" min="0" required value="${x.rate??''}"></div><div class="field"><label>التاريخ والوقت</label><input id="expenseDate" type="datetime-local" value="${x.dateTime||nowLocal()}"></div><div class="field"><label>ملاحظات</label><textarea id="expenseNotes">${esc(x.notes||'')}</textarea></div><div class="form-actions"><button type="button" class="btn btn-light" onclick="back()">إلغاء</button><button type="submit" class="btn btn-primary">حفظ المصروف</button></div></form>`;$('#expenseFormPage').addEventListener('submit',async e=>{e.preventDefault();const amount=Number($('#expenseAmount').value),rate=Number($('#expenseRate').value);if(amount<=0||rate<=0)return toast('أدخل المبلغ وسعر الصرف بشكل صحيح');const old=id?await getRecord('expenses',id):null;const currency=$('#expenseCurrency').value;const conv=currency==='USD'?{usd:amount,iqd:amount*rate}:{usd:amount/rate,iqd:amount};await putRecord('expenses',{id:id||uid('expense'),number:old?.number||await nextNumber('expenseSeq','#E'),type:$('#expenseType').value.trim()||'أخرى',originalAmount:amount,currency,rate,usd:conv.usd,iqd:conv.iqd,dateTime:$('#expenseDate').value,notes:$('#expenseNotes').value.trim(),createdAt:old?.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()});toast('تم حفظ المصروف');go('expenses',{},false)})}
async function renderPayments(a){const ps=await getAll('payments');a.innerHTML=`<div class="section-head"><div class="section-title">الدفعات</div></div>${ps.length?ps.map(p=>`<div class="card"><div class="row"><strong>${esc(p.number)}</strong><span>${esc(p.type)}</span></div><div>${money(p.usd)} $ | ${money(p.iqd)} د.ع</div></div>`).join(''):'<div class="empty">لا توجد دفعات.</div>'}`}
async function deleteCompany(id){const c=await getRecord('companies',id);if(!c)return;if(!confirm('سيتم نقل الشركة إلى سلة المحذوفات. هل تريد المتابعة؟'))return;await putRecord('trash',{id:uid('trash'),originalId:id,type:'company',deletedAt:new Date().toISOString(),data:c});await deleteRecord('companies',id);toast('تم نقل الشركة إلى سلة المحذوفات');render()}
async function deleteExpense(id){const x=await getRecord('expenses',id);if(!x)return;if(!confirm('نقل المصروف إلى سلة المحذوفات؟'))return;await putRecord('trash',{id:uid('trash'),originalId:id,type:'expense',deletedAt:new Date().toISOString(),data:x});await deleteRecord('expenses',id);toast('تم حذف المصروف');render()}
$('#homeBtn')?.addEventListener('click',home);$('#backBtn')?.addEventListener('click',back);
openDB().then(render).catch(e=>{console.error('IndexedDB:',e);const a=$('#app');if(a)a.innerHTML='<div class="empty danger-text">تعذر فتح قاعدة البيانات المحلية.</div>'});
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(console.error));
