// fixed navigation/add-page app.js
const DB_NAME='mahalliDB', DB_VERSION=3;
let db=null, route={name:'home',params:{}}, historyStack=[];
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const money=v=>Number(v||0).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2});
const nowLocal=()=>{const d=new Date(),p=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}T${p(d.getHours())}:${p(d.getMinutes())}`};
const uid=(p='id')=>`${p}_${Date.now()}_${Math.random().toString(36).slice(2,9)}`;
function toast(m){const x=$('#toast');if(!x)return;x.textContent=m;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2200)}
function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,DB_VERSION);r.onupgradeneeded=e=>{const d=e.target.result;['companies','customers','suppliers','purchases','expenses','payments','requests','trash','settings','meta'].forEach(n=>{if(!d.objectStoreNames.contains(n)){const s=d.createObjectStore(n,{keyPath:'id'});s.createIndex('createdAt','createdAt')}})};r.onsuccess=()=>{db=r.result;resolve(db)};r.onerror=()=>reject(r.error)})}
const store=(n,m='readonly')=>db.transaction(n,m).objectStore(n);
const getRecord=(n,id)=>new Promise((res,rej)=>{const r=store(n).get(id);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)});
const getAll=n=>new Promise((res,rej)=>{const r=store(n).getAll();r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)});
const putRecord=(n,o)=>new Promise((res,rej)=>{const r=store(n,'readwrite').put(o);r.onsuccess=()=>res(o);r.onerror=()=>rej(r.error)});
const deleteRecord=(n,id)=>new Promise((res,rej)=>{const r=store(n,'readwrite').delete(id);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)});
async function nextNumber(key,prefix=''){const m=await getRecord('meta',key),v=Number(m?.value||0)+1;await putRecord('meta',{id:key,value:v});return `${prefix}${String(v).padStart(4,'0')}`}
function go(name,params={},push=true){if(push&&route.name!==name)historyStack.push({...route,params:{...route.params}});route={name,params:{...params}};render()}
function back(){const p=historyStack.pop();if(p){route=p;render()}else home()}
function home(){historyStack=[];route={name:'home',params:{}};render()}
window.openAddCompany=()=>go('companyForm',{id:''});
window.openAddCustomer=(companyId='')=>{route={name:'customerForm',params:{id:'',companyId}};historyStack.push({name:'company',params:{id:companyId}});render();};
window.openAddExpense=()=>go('expenseForm',{id:''});
window.editCompany=id=>go('companyForm',{id});
window.editCustomer=(id,companyId='')=>go('customerForm',{id,companyId});
window.editExpense=id=>go('expenseForm',{id});
window.openCompany=id=>go('company',{id});
window.openCustomer=id=>go('customer',{id});
window.openPayments=()=>go('payments');
window.placeholder=t=>{const m=$('#modal');if(!m)return;m.classList.remove('hidden');m.innerHTML=`<div class="modal-box"><div class="modal-title">${esc(t)}</div><p class="muted">هذه الوحدة ستُستكمل في المرحلة التالية.</p><button class="btn btn-primary" onclick="closeModal()">حسنًا</button></div>`};
window.closeModal=()=>{const m=$('#modal');if(!m)return;m.classList.add('hidden');m.innerHTML=''};
async function render(){if(!db)return;const a=$('#app');if(!a)return;$('#backBtn')?.classList.toggle('hidden',route.name==='home');$('#homeBtn')?.classList.toggle('hidden',route.name==='home');a.innerHTML='';switch(route.name){case'home':return renderHome(a);case'companies':return renderCompanies(a);case'company':return renderCompany(a,route.params.id);case'companyForm':return renderCompanyForm(a,route.params.id);case'customerForm':return renderCustomerForm(a,route.params.id,route.params.companyId);case'customer':return renderCustomer(a,route.params.id);case'expenses':return renderExpenses(a);case'expenseForm':return renderExpenseForm(a,route.params.id);case'payments':return renderPayments(a);case'suppliers':return renderSuppliers(a);case'supplierForm':return renderSupplierForm(a,route.params.id);case'purchases':return renderPurchases(a);case'purchaseForm':return renderPurchaseForm(a,route.params.id);case'reports':return renderReports(a);case'search':return renderSearch(a);case'settings':return renderSettings(a);case'trash':return renderTrash(a);default:return home()}}
function renderHome(a){a.innerHTML=`<div class="home-title">محلّي</div><div class="home-grid"><button class="home-card" onclick="go('companies')"><span class="emoji">🏢</span>الشركات والعملاء</button><button class="home-card" onclick="go('purchases')"><span class="emoji">🛒</span>المشتريات</button><button class="home-card" onclick="go('suppliers')"><span class="emoji">🏭</span>الموردون</button><button class="home-card" onclick="go('expenses')"><span class="emoji">💸</span>المصروفات</button><button class="home-card" onclick="openPayments()"><span class="emoji">💰</span>الدفعات</button><button class="home-card" onclick="go('reports')"><span class="emoji">📊</span>التقارير</button><button class="home-card" onclick="go('search')"><span class="emoji">🔍</span>البحث</button><button class="home-card" onclick="go('settings')"><span class="emoji">⚙️</span>الإعدادات والنسخ الاحتياطي</button></div>`}
async function renderCompanies(a){const cs=(await getAll('companies')).sort((x,y)=>String(y.createdAt||'').localeCompare(String(x.createdAt||'')));a.innerHTML=`<div class="section-head"><div class="section-title">الشركات والعملاء</div><button class="btn btn-primary" onclick="openAddCompany()">＋ إضافة شركة</button></div><input id="companySearch" class="search" placeholder="بحث باسم الشركة"><div id="company-list">${cs.length?cs.map(c=>`<div class="card searchable" data-search="${esc(c.name)}"><div class="row"><div><strong>${esc(c.name)}</strong><div class="muted">${esc(c.phone||'')}</div></div><div class="amount">${money(c.totalUSD)} $<br>${money(c.totalIQD)} د.ع</div></div><div class="list-actions"><button class="btn btn-light" onclick="openCompany('${c.id}')">فتح</button><button class="btn btn-light" onclick="editCompany('${c.id}')">تعديل</button><button class="btn btn-danger" onclick="deleteCompany('${c.id}')">حذف</button></div></div>`).join(''):'<div class="empty">لا توجد شركات بعد.</div>'}</div>`;$('#companySearch')?.addEventListener('input',e=>{const q=e.target.value.toLowerCase();document.querySelectorAll('#company-list .searchable').forEach(x=>x.style.display=String(x.dataset.search||'').toLowerCase().includes(q)?'':'none')})}
async function renderCompanyForm(a,id){const c=id?await getRecord('companies',id):{};a.innerHTML=`<div class="section-head"><div class="section-title">${id?'تعديل الشركة':'إضافة شركة'}</div></div><form id="companyFormPage" class="form"><div class="field"><label>اسم الشركة *</label><input id="companyName" required value="${esc(c.name||'')}"></div><div class="field"><label>الهاتف</label><input id="companyPhone" value="${esc(c.phone||'')}"></div><div class="field"><label>العنوان</label><input id="companyAddress" value="${esc(c.address||'')}"></div><div class="field"><label>ملاحظات</label><textarea id="companyNotes">${esc(c.notes||'')}</textarea></div><div class="form-actions"><button type="button" class="btn btn-light" onclick="back()">إلغاء</button><button type="submit" class="btn btn-primary">حفظ الشركة</button></div></form>`;$('#companyFormPage').addEventListener('submit',async e=>{e.preventDefault();const name=$('#companyName').value.trim();if(!name)return toast('اسم الشركة مطلوب');const old=id?await getRecord('companies',id):null;await putRecord('companies',{id:id||uid('company'),name,phone:$('#companyPhone').value.trim(),address:$('#companyAddress').value.trim(),notes:$('#companyNotes').value.trim(),createdAt:old?.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString(),totalUSD:old?.totalUSD||0,totalIQD:old?.totalIQD||0});toast('تم حفظ الشركة');go('companies',{},false)})}
async function renderCustomerForm(a,id,companyId){const c=id?await getRecord('customers',id):{};const cid=companyId||c.companyId||'';a.innerHTML=`<div class="section-head"><div class="section-title">${id?'تعديل العميل':'إضافة عميل'}</div></div><form id="customerFormPage" class="form"><div class="field"><label>اسم العميل *</label><input id="customerName" required value="${esc(c.name||'')}"></div><div class="field"><label>الهاتف</label><input id="customerPhone" value="${esc(c.phone||'')}"></div><div class="field"><label>العنوان</label><input id="customerAddress" value="${esc(c.address||'')}"></div><div class="field"><label>ملاحظات</label><textarea id="customerNotes">${esc(c.notes||'')}</textarea></div><div class="form-actions"><button type="button" class="btn btn-light" onclick="back()">إلغاء</button><button type="submit" class="btn btn-primary">حفظ العميل</button></div></form>`;$('#customerFormPage').addEventListener('submit',async e=>{e.preventDefault();const name=$('#customerName').value.trim();if(!name)return toast('اسم العميل مطلوب');const old=id?await getRecord('customers',id):null;const customer={id:id||uid('customer'),name,phone:$('#customerPhone').value.trim(),address:$('#customerAddress').value.trim(),notes:$('#customerNotes').value.trim(),companyId:cid||old?.companyId||null,accountNumber:old?.accountNumber||null,accountStatus:old?.accountStatus||'مفتوح',createdAt:old?.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()};await putRecord('customers',customer);toast('تم حفظ العميل');customer.companyId?go('company',{id:customer.companyId},false):go('companies',{},false)})}
async function renderCompany(a,id){
 const c=await getRecord('companies',id);if(!c)return home();
 const cs=(await getAll('customers')).filter(x=>x.companyId===id).sort((x,y)=>String(y.createdAt||'').localeCompare(String(x.createdAt||'')));
 a.innerHTML=`<div class="section-head"><div class="section-title">${esc(c.name)}</div><button id="editCompanyBtn" class="btn btn-light">تعديل</button></div>
 <div class="total-box"><div class="total">الدولار<strong>${money(c.totalUSD)} $</strong></div><div class="total">الدينار<strong>${money(c.totalIQD)} د.ع</strong></div></div>
 <div class="actions" style="margin-bottom:12px"><button id="addCustomerBtn" type="button" class="btn btn-primary" onclick="window.openAddCustomer('${esc(id)}')">＋ إضافة عميل</button><button id="addRequestBtn" type="button" class="btn btn-primary">＋ إضافة طلب</button><button id="addCompanyPaymentBtn" type="button" class="btn btn-success">💰 إضافة دفعة للشركة</button></div>
 ${cs.length?cs.map(x=>`<div class="card"><div class="row"><div><strong>${esc(x.name)}</strong><div class="muted">${esc(x.phone||'')}</div></div></div><div class="list-actions"><button class="btn btn-light customer-open" data-id="${esc(x.id)}">فتح</button><button class="btn btn-light customer-edit" data-id="${esc(x.id)}">تعديل</button></div></div>`).join(''):'<div class="empty">لا يوجد عملاء لهذه الشركة.</div>'}`;
 $('#editCompanyBtn')?.addEventListener('click',()=>window.editCompany(id));
 $('#addCustomerBtn')?.addEventListener('click',()=>window.openAddCustomer(id));
 $('#addCustomerBtn')?.addEventListener('touchend',e=>{e.preventDefault();window.openAddCustomer(id)},{passive:false});
 $('#addRequestBtn')?.addEventListener('click',()=>window.placeholder('إضافة طلب'));
 $('#addCompanyPaymentBtn')?.addEventListener('click',()=>window.placeholder('إضافة دفعة للشركة'));
 a.querySelectorAll('.customer-open').forEach(b=>b.addEventListener('click',()=>window.openCustomer(b.dataset.id)));
 a.querySelectorAll('.customer-edit').forEach(b=>b.addEventListener('click',()=>window.editCustomer(b.dataset.id,id)));
}
async function renderCustomer(a,id){const c=await getRecord('customers',id);if(!c)return home();a.innerHTML=`<div class="section-head"><div class="section-title">${esc(c.name)}</div><button class="btn btn-light" onclick="editCustomer('${id}','${c.companyId||''}')">تعديل</button></div><div class="empty">صفحة حساب العميل الأساسية ستُستكمل في المرحلة التالية.</div>`}
async function renderExpenses(a){const xs=(await getAll('expenses')).sort((x,y)=>String(y.dateTime||'').localeCompare(String(x.dateTime||'')));a.innerHTML=`<div class="section-head"><div class="section-title">المصروفات</div><button class="btn btn-primary" onclick="openAddExpense()">＋ إضافة مصروف</button></div>${xs.length?xs.map(x=>`<div class="card"><div class="row"><strong>#${esc(x.number)}</strong><span>${esc(x.type)}</span></div><div>${money(x.usd)} $ | ${money(x.iqd)} د.ع</div><div class="muted">${esc(x.dateTime||'')}</div><div class="list-actions"><button class="btn btn-light" onclick="editExpense('${x.id}')">تعديل</button><button class="btn btn-danger" onclick="deleteExpense('${x.id}')">حذف</button></div></div>`).join(''):'<div class="empty">لا توجد مصروفات.</div>'}`}
async function renderExpenseForm(a,id){const x=id?await getRecord('expenses',id):{};a.innerHTML=`<div class="section-head"><div class="section-title">${id?'تعديل المصروف':'إضافة مصروف'}</div></div><form id="expenseFormPage" class="form"><div class="field"><label>النوع</label><input id="expenseType" value="${esc(x.type||'أخرى')}"></div><div class="field"><label>المبلغ *</label><input id="expenseAmount" type="number" step="0.01" min="0" required value="${x.originalAmount??''}"></div><div class="field"><label>العملة</label><select id="expenseCurrency"><option value="USD" ${x.currency==='USD'?'selected':''}>USD</option><option value="IQD" ${x.currency==='IQD'?'selected':''}>IQD</option></select></div><div class="field"><label>سعر الصرف *</label><input id="expenseRate" type="number" step="0.01" min="0" required value="${x.rate??''}"></div><div class="field"><label>التاريخ والوقت</label><input id="expenseDate" type="datetime-local" value="${x.dateTime||nowLocal()}"></div><div class="field"><label>ملاحظات</label><textarea id="expenseNotes">${esc(x.notes||'')}</textarea></div><div class="form-actions"><button type="button" class="btn btn-light" onclick="back()">إلغاء</button><button type="submit" class="btn btn-primary">حفظ المصروف</button></div></form>`;$('#expenseFormPage').addEventListener('submit',async e=>{e.preventDefault();const amount=Number($('#expenseAmount').value),rate=Number($('#expenseRate').value);if(amount<=0||rate<=0)return toast('أدخل المبلغ وسعر الصرف بشكل صحيح');const old=id?await getRecord('expenses',id):null;const currency=$('#expenseCurrency').value;const conv=currency==='USD'?{usd:amount,iqd:amount*rate}:{usd:amount/rate,iqd:amount};await putRecord('expenses',{id:id||uid('expense'),number:old?.number||await nextNumber('expenseSeq','#E'),type:$('#expenseType').value.trim()||'أخرى',originalAmount:amount,currency,rate,usd:conv.usd,iqd:conv.iqd,dateTime:$('#expenseDate').value,notes:$('#expenseNotes').value.trim(),createdAt:old?.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()});toast('تم حفظ المصروف');go('expenses',{},false)})}
async function renderPayments(a){const ps=await getAll('payments');a.innerHTML=`<div class="section-head"><div class="section-title">الدفعات</div></div>${ps.length?ps.map(p=>`<div class="card"><div class="row"><strong>${esc(p.number)}</strong><span>${esc(p.type)}</span></div><div>${money(p.usd)} $ | ${money(p.iqd)} د.ع</div></div>`).join(''):'<div class="empty">لا توجد دفعات.</div>'}`}

window.openAddSupplier=()=>go('supplierForm',{id:''});
window.openAddPurchase=()=>go('purchaseForm',{id:''});
window.editSupplier=id=>go('supplierForm',{id});
window.editPurchase=id=>go('purchaseForm',{id});

async function renderSuppliers(a){const xs=(await getAll('suppliers')).sort((x,y)=>String(y.createdAt||'').localeCompare(String(x.createdAt||'')));a.innerHTML=`<div class="section-head"><div class="section-title">الموردون</div><button class="btn btn-primary" onclick="openAddSupplier()">＋ إضافة مورد</button></div><input id="supplierSearch" class="search" placeholder="بحث باسم المورد"><div id="supplier-list">${xs.length?xs.map(x=>`<div class="card searchable" data-search="${esc(x.name)}"><div class="row"><div><strong>${esc(x.name)}</strong><div class="muted">${esc(x.phone||'')}</div></div><div class="amount">${money(x.totalPurchasesUSD||0)} $<br>${money(x.totalPurchasesIQD||0)} د.ع</div></div><div class="list-actions"><button class="btn btn-light" onclick="editSupplier('${x.id}')">تعديل</button></div></div>`).join(''):'<div class="empty">لا يوجد موردون بعد.</div>'}</div>`;$('#supplierSearch')?.addEventListener('input',e=>{const q=e.target.value.toLowerCase();document.querySelectorAll('#supplier-list .searchable').forEach(x=>x.style.display=String(x.dataset.search||'').toLowerCase().includes(q)?'':'none')})}
async function renderSupplierForm(a,id){const x=id?await getRecord('suppliers',id):{};a.innerHTML=`<div class="section-head"><div class="section-title">${id?'تعديل المورد':'إضافة مورد'}</div></div><form id="supplierFormPage" class="form"><div class="field"><label>اسم المورد *</label><input id="supplierName" required value="${esc(x.name||'')}"></div><div class="field"><label>الهاتف</label><input id="supplierPhone" value="${esc(x.phone||'')}"></div><div class="field"><label>العنوان</label><input id="supplierAddress" value="${esc(x.address||'')}"></div><div class="field"><label>ملاحظات</label><textarea id="supplierNotes">${esc(x.notes||'')}</textarea></div><div class="form-actions"><button type="button" class="btn btn-light" onclick="back()">إلغاء</button><button class="btn btn-primary">حفظ المورد</button></div></form>`;$('#supplierFormPage').addEventListener('submit',async e=>{e.preventDefault();const name=$('#supplierName').value.trim();if(!name)return toast('اسم المورد مطلوب');const old=id?await getRecord('suppliers',id):null;await putRecord('suppliers',{id:id||uid('supplier'),name,phone:$('#supplierPhone').value.trim(),address:$('#supplierAddress').value.trim(),notes:$('#supplierNotes').value.trim(),totalPurchasesUSD:old?.totalPurchasesUSD||0,totalPurchasesIQD:old?.totalPurchasesIQD||0,createdAt:old?.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()});toast('تم حفظ المورد');go('suppliers',{},false)})}
async function renderPurchases(a){const xs=(await getAll('purchases')).sort((x,y)=>String(y.dateTime||y.createdAt||'').localeCompare(String(x.dateTime||x.createdAt||'')));a.innerHTML=`<div class="section-head"><div class="section-title">المشتريات</div><button class="btn btn-primary" onclick="openAddPurchase()">＋ إضافة شراء</button></div>${xs.length?xs.map(x=>`<div class="card"><div class="row"><strong>#${esc(x.number||'')}</strong><span>${esc(x.category||'مشتريات أخرى')}</span></div><div>${money(x.usd||0)} $ | ${money(x.iqd||0)} د.ع</div><div class="muted">${esc(x.dateTime||'')} ${x.supplierName?`| ${esc(x.supplierName)}`:''}</div><div class="list-actions"><button class="btn btn-light" onclick="editPurchase('${x.id}')">تعديل</button></div></div>`).join(''):'<div class="empty">لا توجد مشتريات بعد.</div>'}`}
async function renderPurchaseForm(a,id){const x=id?await getRecord('purchases',id):{};const suppliers=await getAll('suppliers');a.innerHTML=`<div class="section-head"><div class="section-title">${id?'تعديل المشتريات':'إضافة شراء'}</div></div><form id="purchaseFormPage" class="form"><div class="field"><label>المورد</label><select id="purchaseSupplier"><option value="">بدون مورد</option>${suppliers.map(s=>`<option value="${s.id}" ${x.supplierId===s.id?'selected':''}>${esc(s.name)}</option>`).join('')}</select></div><div class="field"><label>الفئة</label><select id="purchaseCategory"><option>ألواح الكوارتز</option><option>مواد أولية للمرمر</option><option>الأحواض</option><option>مشتريات أخرى</option></select></div><div class="field"><label>اسم/وصف المادة *</label><input id="purchaseName" required value="${esc(x.name||'')}"></div><div class="field"><label>الكمية *</label><input id="purchaseQty" type="number" step="1" min="1" required value="${x.quantity??1}"></div><div class="field"><label>سعر الوحدة بالدولار *</label><input id="purchaseUnitUSD" type="number" step="1" min="1" required value="${x.unitUSD??''}"></div><div class="field"><label>سعر الصرف *</label><input id="purchaseRate" type="number" step="0.01" min="1" required value="${x.rate??''}"></div><div class="field"><label>التاريخ والوقت</label><input id="purchaseDate" type="datetime-local" value="${x.dateTime||nowLocal()}"></div><div class="field"><label>رقم فاتورة المورد</label><input id="purchaseInvoice" value="${esc(x.supplierInvoiceNumber||'')}"></div><div class="form-actions"><button type="button" class="btn btn-light" onclick="back()">إلغاء</button><button class="btn btn-primary">حفظ الشراء</button></div></form>`;if(x.category)$('#purchaseCategory').value=x.category;$('#purchaseFormPage').addEventListener('submit',async e=>{e.preventDefault();const q=Number($('#purchaseQty').value),u=Number($('#purchaseUnitUSD').value),r=Number($('#purchaseRate').value);if(q<=0||u<=0||r<=0)return toast('أدخل الكمية والسعر وسعر الصرف بشكل صحيح');const old=id?await getRecord('purchases',id):null;const sid=$('#purchaseSupplier').value;const sup=sid?await getRecord('suppliers',sid):null;const usd=q*u,iqd=usd*r;await putRecord('purchases',{id:id||uid('purchase'),number:old?.number||await nextNumber('purchaseSeq','#P'),supplierId:sid||null,supplierName:sup?.name||'',supplierInvoiceNumber:$('#purchaseInvoice').value.trim(),category:$('#purchaseCategory').value,name:$('#purchaseName').value.trim(),quantity:q,unitUSD:u,rate:r,usd,iqd,dateTime:$('#purchaseDate').value,createdAt:old?.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()});toast('تم حفظ الشراء');go('purchases',{},false)})}
async function renderReports(a){const [req,pay,pur,exp]=await Promise.all([getAll('requests'),getAll('payments'),getAll('purchases'),getAll('expenses')]);const sum=k=>arr=>arr.reduce((t,x)=>t+Number(x[k]||0),0);a.innerHTML=`<div class="section-head"><div class="section-title">التقارير</div></div><div class="card"><strong>ملخص عام</strong><div class="report-grid"><div>الطلبات<br><b>${req.length}</b></div><div>الدفعات<br><b>${money(sum('usd')(pay))} $</b></div><div>المشتريات<br><b>${money(sum('usd')(pur))} $</b></div><div>المصروفات<br><b>${money(sum('usd')(exp))} $</b></div></div></div><div class="card"><strong>التقارير المتاحة</strong><div class="list-actions"><button class="btn btn-light" onclick="renderReportPeriod('daily')">يومي</button><button class="btn btn-light" onclick="renderReportPeriod('monthly')">شهري</button><button class="btn btn-light" onclick="renderReportPeriod('annual')">سنوي</button></div><div id="reportPeriod" class="muted">اختر الفترة لعرض العمليات المسجلة.</div></div>`}
window.renderReportPeriod=async type=>{const a=$('#reportPeriod');if(!a)return;const label=type==='daily'?'اليوم':type==='monthly'?'هذا الشهر':'هذه السنة';const now=new Date(),p=n=>String(n).padStart(2,'0');const prefix=type==='daily'?`${now.getFullYear()}-${p(now.getMonth()+1)}-${p(now.getDate())}`:type==='monthly'?`${now.getFullYear()}-${p(now.getMonth()+1)}`:`${now.getFullYear()}`;const [pay,exp,pur]=await Promise.all([getAll('payments'),getAll('expenses'),getAll('purchases')]);const match=x=>String(x.dateTime||'').startsWith(prefix);const s=(arr,k)=>arr.filter(match).reduce((t,x)=>t+Number(x[k]||0),0);a.innerHTML=`<div>${label}: ${pay.filter(match).length} دفعات، ${pur.filter(match).length} مشتريات، ${exp.filter(match).length} مصروفات</div><div>الدفعات: ${money(s(pay,'usd'))} $</div><div>المشتريات: ${money(s(pur,'usd'))} $</div><div>المصروفات: ${money(s(exp,'usd'))} $</div>`}
async function renderSearch(a){a.innerHTML=`<div class="section-head"><div class="section-title">البحث</div></div><input id="globalSearch" class="search" placeholder="ابحث بالاسم أو الرقم أو الفاتورة أو العملية"><div id="searchResults" class="empty">اكتب كلمة البحث لعرض النتائج.</div>`;$('#globalSearch').addEventListener('input',async e=>{const q=e.target.value.trim().toLowerCase();const out=$('#searchResults');if(!q){out.className='empty';out.textContent='اكتب كلمة البحث لعرض النتائج.';return}const defs=[['الشركات','companies',x=>[x.name,x.phone].join(' ')],['العملاء','customers',x=>[x.name,x.phone].join(' ')],['الموردون','suppliers',x=>[x.name,x.phone].join(' ')],['الطلبات','requests',x=>[x.number,x.code,x.product,x.customerName].join(' ')],['الدفعات','payments',x=>[x.number,x.receiptNumber,x.type,x.entityName].join(' ')],['المشتريات','purchases',x=>[x.number,x.supplierInvoiceNumber,x.supplierName,x.name,x.category].join(' ')],['المصروفات','expenses',x=>[x.number,x.type,x.notes].join(' ')]];let html='';for(const [label,st,fn] of defs){const rows=(await getAll(st)).filter(x=>fn(x).toLowerCase().includes(q));if(rows.length)html+=`<div class="card"><strong>${label}</strong>${rows.slice(0,30).map(x=>`<div class="row" style="padding:8px 0;border-top:1px solid #eee"><span>${esc(x.name||x.number||x.type||'سجل')}</span><span class="muted">${esc(x.number||x.dateTime||'')}</span></div>`).join('')}</div>`}out.className=html?'':'empty';out.innerHTML=html||'لا توجد نتائج.'})}
async function renderSettings(a){const types=(await getRecord('settings','expenseTypes'))?.value||['نقل','أجور عمال','كهرباء','ماء','إيجار','صيانة','وقود','أدوات ومستلزمات','أخرى'];const mats=(await getRecord('settings','marbleMaterials'))?.value||['بولستر','جلكود','طوز','أصباغ','يبراغ','كرابول','لمعات','معجون'];a.innerHTML=`<div class="section-head"><div class="section-title">الإعدادات والنسخ الاحتياطي</div></div><div class="card"><strong>بيانات المؤسسة</strong><div class="field"><label>اسم المؤسسة</label><input id="institutionName" value="${esc((await getRecord('settings','institutionName'))?.value||'محلّي')}"></div><button class="btn btn-primary" onclick="saveInstitution()">حفظ</button></div><div class="card"><strong>أنواع المصروفات</strong><div>${types.map(x=>`<span class="tag">${esc(x)}</span>`).join(' ')}</div><div class="form-actions"><input id="newExpenseType" placeholder="نوع جديد"><button class="btn btn-light" onclick="addExpenseType()">إضافة</button></div></div><div class="card"><strong>مواد المرمر</strong><div>${mats.map(x=>`<span class="tag">${esc(x)}</span>`).join(' ')}</div><div class="form-actions"><input id="newMarbleMaterial" placeholder="مادة جديدة"><button class="btn btn-light" onclick="addMarbleMaterial()">إضافة</button></div></div><div class="card"><strong>النسخ الاحتياطي</strong><div class="list-actions"><button class="btn btn-primary" onclick="exportBackup()">تصدير نسخة احتياطية</button><label class="btn btn-light">استعادة نسخة<input id="backupFile" type="file" accept="application/json" hidden onchange="importBackup(this.files[0])"></label><button class="btn btn-light" onclick="go('trash')">سلة المحذوفات</button></div><p class="muted">النسخة تشمل بيانات التطبيق والإعدادات وسجلات الحذف.</p></div>`}
window.saveInstitution=async()=>{await putRecord('settings',{id:'institutionName',value:$('#institutionName').value.trim()||'محلّي'});toast('تم حفظ الإعداد')};
window.addExpenseType=async()=>{const v=$('#newExpenseType').value.trim();if(!v)return;const o=await getRecord('settings','expenseTypes');const a=o?.value||[];if(!a.includes(v))a.push(v);await putRecord('settings',{id:'expenseTypes',value:a});render()};
window.addMarbleMaterial=async()=>{const v=$('#newMarbleMaterial').value.trim();if(!v)return;const o=await getRecord('settings','marbleMaterials');const a=o?.value||[];if(!a.includes(v))a.push(v);await putRecord('settings',{id:'marbleMaterials',value:a});render()};
async function exportBackup(){const names=['companies','customers','suppliers','purchases','expenses','payments','requests','trash','settings','meta'];const data={app:'محلّي',version:1,exportedAt:new Date().toISOString(),stores:{}};for(const n of names)data.stores[n]=await getAll(n);const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`mahalli-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('تم إنشاء النسخة الاحتياطية')}
async function importBackup(file){if(!file)return;try{const data=JSON.parse(await file.text());if(!data?.stores||typeof data.stores!=='object')throw Error('invalid');if(!confirm('سيتم استبدال البيانات الحالية بالنسخة الاحتياطية. هل تريد المتابعة؟'))return;const names=['companies','customers','suppliers','purchases','expenses','payments','requests','trash','settings','meta'];for(const n of names){const rows=Array.isArray(data.stores[n])?data.stores[n]:[];const old=await getAll(n);for(const r of old)await deleteRecord(n,r.id);for(const r of rows)await putRecord(n,r)}toast('تمت استعادة النسخة الاحتياطية');render()}catch(e){console.error(e);toast('ملف النسخة الاحتياطية غير صالح')}}
async function renderTrash(a){const xs=(await getAll('trash')).sort((x,y)=>String(y.deletedAt||'').localeCompare(String(x.deletedAt||'')));a.innerHTML=`<div class="section-head"><div class="section-title">سلة المحذوفات</div></div>${xs.length?xs.map(x=>`<div class="card"><div class="row"><strong>${esc(x.type)}</strong><span class="muted">${esc(x.deletedAt||'')}</span></div><div>${esc(x.data?.name||x.data?.number||x.originalId)}</div><div class="list-actions"><button class="btn btn-light" onclick="restoreTrash('${x.id}')">استعادة</button><button class="btn btn-danger" onclick="permanentTrash('${x.id}')">حذف نهائي</button></div></div>`).join(''):'<div class="empty">سلة المحذوفات فارغة.</div>'}`}
window.restoreTrash=async tid=>{const t=await getRecord('trash',tid);if(!t)return;const target=t.type==='company'?'companies':t.type==='expense'?'expenses':t.type==='supplier'?'suppliers':t.type==='purchase'?'purchases':null;if(!target)return toast('لا يمكن استعادة هذا النوع حالياً');await putRecord(target,t.data);await deleteRecord('trash',tid);toast('تمت الاستعادة');render()};
window.permanentTrash=async tid=>{if(!confirm('حذف نهائي؟ لا يمكن التراجع.'))return;await deleteRecord('trash',tid);render()};
async function deleteCompany(id){const c=await getRecord('companies',id);if(!c)return;if(!confirm('سيتم نقل الشركة إلى سلة المحذوفات. هل تريد المتابعة؟'))return;await putRecord('trash',{id:uid('trash'),originalId:id,type:'company',deletedAt:new Date().toISOString(),data:c});await deleteRecord('companies',id);toast('تم نقل الشركة إلى سلة المحذوفات');render()}
async function deleteExpense(id){const x=await getRecord('expenses',id);if(!x)return;if(!confirm('نقل المصروف إلى سلة المحذوفات؟'))return;await putRecord('trash',{id:uid('trash'),originalId:id,type:'expense',deletedAt:new Date().toISOString(),data:x});await deleteRecord('expenses',id);toast('تم حذف المصروف');render()}
$('#homeBtn')?.addEventListener('click',home);$('#backBtn')?.addEventListener('click',back);
openDB().then(render).catch(e=>{console.error('IndexedDB:',e);const a=$('#app');if(a)a.innerHTML='<div class="empty danger-text">تعذر فتح قاعدة البيانات المحلية.</div>'});
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(console.error));
